@InterviewProject_HostAddress = http://localhost:5109

GET {{InterviewProject_HostAddress}}/api/weatherforecast/
Accept: application/json

###

POST {{InterviewProject_HostAddress}}/api/account/login/
Accept: application/json
